### ISSUE TITLE
Navigation Bug

### ISSUE THREAD

**Issue by HackNishant** [RossellaFer/fcc-portfolio#6]
There is a bug in Navigation, Due to which user is not able to access About, Portfolio, and Contact from blog section, to see these section's user has to come back to home page by clicking your logo.

![Screenshot 2022-09-25 132945](https://user-images.githubusercontent.com/90667262/192134026-934b13e0-bd8a-410b-bf85-6923b0e40b2f.png)

**Comment by RossellaFer** [comment]
@HackNishant thanks for flagging this! I have made a change that fixes the bug
